/**
 * Every visitor-facing string. Albanian first (the audience is in Tirana), then English and French.
 * Rules: short sentences, concrete verbs, one label per intent, no invented facts.
 * Prices, stock and delivery fees never live here: they come from the admin.
 * No em or en dashes anywhere (DESIGN.md). The brand line "Elegance that endures" stays in English
 * in every language (Luca, 2026-10-01).
 */
export type Lang = 'sq' | 'en' | 'fr';
export const LANGS: readonly Lang[] = ['sq', 'en', 'fr'];
export const isLang = (v: unknown): v is Lang => v === 'sq' || v === 'en' || v === 'fr';

const TAGLINE = 'Elegance that endures';
const MONTHS_SQ = ['janar', 'shkurt', 'mars', 'prill', 'maj', 'qershor', 'korrik', 'gusht', 'shtator', 'tetor', 'nëntor', 'dhjetor'];
const MONTHS_EN = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
const MONTHS_FR = ['janvier', 'février', 'mars', 'avril', 'mai', 'juin', 'juillet', 'août', 'septembre', 'octobre', 'novembre', 'décembre'];
/** French sets a non-breaking space before a colon, so the colon never starts a line. */
const NBSP = String.fromCharCode(160);

/** A follower count the way Instagram shows it, rounded down: 26 431 is 26,4 mijë, 26.4K, 26,4 k. */
function compact(n: number, lang: Lang): string {
  if (n < 1000) return String(n);
  const million = n >= 1_000_000;
  const v = Math.floor(n / (million ? 100_000 : 100)) / 10;
  const s = Number.isInteger(v) ? String(v) : v.toFixed(1);
  if (lang === 'en') return `${s}${million ? 'M' : 'K'}`;
  const d = s.replace('.', ',');
  return lang === 'fr' ? `${d}${NBSP}${million ? 'M' : 'k'}` : `${d} ${million ? 'milion' : 'mijë'}`;
}

const sq = {
  lang: 'sq' as Lang,
  langName: 'Shqip',
  langShort: 'SQ',
  meta: {
    homeTitle: 'Fustane mbrëmjeje në Tiranë · Çmime në lek · Dresses by Greta',
    homeDescription: 'Fustane mbrëmjeje, mature, për dasma dhe koktej nga dyqani në Tiranë, me çmime në lek. Zgjidh masën, porosite online dhe paguaj në dorëzim. Edhe me qera.',
    shopTitle: 'Fustane online · Pagesë në dorëzim · Dresses by Greta',
    shopDescription: 'Të gjitha fustanet e Dresses by Greta me çmimin dhe masat në gjendje. Porosit online dhe paguaj në dorëzim.',
    sizeTitle: (size: string) => `Fustane në masën ${size}, Dresses by Greta`,
    checkoutTitle: 'Porosia, Dresses by Greta',
    notFoundTitle: 'Faqja nuk u gjet, Dresses by Greta',
  },
  occasions: {
    heading: 'Sipas rastit',
    usp: 'Çmime në lek · Pagesë në dorëzim · Dyqani në Tiranë',
    rentAsk: 'Pyet për qira në Instagram',
    evening: {
      label: 'Fustane mbrëmjeje',
      title: 'Fustane mbrëmjeje në Tiranë · Çmime në lek · Dresses by Greta',
      h1: 'Fustane mbrëmjeje në Tiranë',
      description: 'Fustane të gjata mbrëmjeje nga dyqani në Tiranë, me çmimin në lek dhe masat në gjendje. Porosit online dhe paguaj në dorëzim.',
      intro: 'Fustane të gjata për gala, festa dhe ceremoni, nga dyqani ynë në Tiranë. Çdo fustan ka çmimin në lek dhe masat që kemi në gjendje. Zgjidh masën, porosite online dhe paguaj kur të vjen, ose eja ta provosh në dyqan.',
    },
    prom: {
      label: 'Fustane mature',
      title: 'Fustane mature në Tiranë · Çmime në lek · Dresses by Greta',
      h1: 'Fustane për maturë',
      description: 'Fustane për mbrëmjen e maturës, të gjata dhe të shkurtra, me çmimin në lek. Porosit online në Tiranë dhe paguaj në dorëzim.',
      intro: 'Fustane për mbrëmjen e maturës, të gjata ose të shkurtra. Shiko çmimin dhe masat në gjendje, porosite online dhe paguaj në dorëzim, ose provoje në dyqan në Tiranë para mbrëmjes.',
    },
    wedding: {
      label: 'Fustane për dasma',
      title: 'Fustane për dasma në Tiranë · Çmime në lek · Dresses by Greta',
      h1: 'Fustane për dasma',
      description: 'Fustane për të ftuarat në dasma, fejesa dhe ceremoni, me çmimin në lek dhe masat në gjendje. Pagesë në dorëzim.',
      intro: 'Fustane për të ftuarat në dasma, fejesa dhe ceremoni familjare. Çdo fustan ka çmimin në lek dhe masat që kemi në gjendje. Porosite online dhe paguaj kur të vjen.',
    },
    cocktail: {
      label: 'Fustane koktej',
      title: 'Fustane koktej në Tiranë · Çmime në lek · Dresses by Greta',
      h1: 'Fustane koktej',
      description: 'Fustane koktej, mini dhe midi, për ditëlindje, darka dhe festa. Çmime në lek, porosi online dhe pagesë në dorëzim.',
      intro: 'Fustane mini dhe midi për ditëlindje, darka dhe festa. Shiko çmimin dhe masat në gjendje, porosite online dhe paguaj në dorëzim.',
    },
    rental: {
      label: 'Fustane me qera',
      title: 'Fustane me qera në Tiranë · Dresses by Greta',
      h1: 'Fustane me qera në Tiranë',
      description: 'Fustane mbrëmjeje me qera në Tiranë nga Dresses by Greta. Na shkruani në Instagram me fustanin, masën dhe datën e eventit.',
      intro: 'Fustanet tona mund t\'i merrni edhe me qera për një mbrëmje. Na shkruani në Instagram me emrin e fustanit, masën dhe datën e eventit, dhe ju konfirmojmë çmimin e qirasë dhe nëse fustani është i lirë atë ditë. Çdo fustan më poshtë mund ta blini edhe online.',
    },
  },
  a11y: {
    skip: 'Kalo te përmbajtja',
    wordmark: 'Dresses by Greta, kryefaqja',
    sizeIndex: 'Masat',
    spreads: 'Fustanet',
    gallery: 'Fotot e fustanit',
    close: 'Mbyll',
    qtyDown: 'Një më pak',
    qtyUp: 'Një më shumë',
    zoom: 'Shiko foton të plotë',
    photoOf: (n: number, total: number) => `Foto ${n} nga ${total}`,
    prev: 'Foto e mëparshme',
    next: 'Foto tjetër',
    removeFilter: 'Hiq filtrin',
  },
  demo: 'Të dhëna demo: çmimet dhe gjendja janë shembuj për testim, jo të dyqanit.',
  nav: {
    menu: 'Menu',
    close: 'Mbyll',
    search: 'Kërko',
    bag: 'Çanta',
    region: 'Gjuha',
    shop: 'Dyqani',
    lookbook: 'Shop',
    all: 'Të gjitha fustanet',
    bySize: 'Sipas masës',
    visit: 'Dyqani në Tiranë',
    instagram: 'Instagram',
  },
  hero: {
    wordmark: 'Dresses by Greta',
    cta: 'Shiko fustanet',
    alt: 'Fustan i gjatë me tyl rozë dhe jeshil të zbehtë, në një kopsht me trëndafila',
  },
  categories: { all: 'Të gjitha', gowns: 'Të gjata', mini: 'Mini & midi', black: 'Të zeza', tv: 'Në TV', new: 'Të reja' },
  sizes: {
    title: 'Sipas masës',
    all: 'Të gjitha',
    count: (n: number) => (n === 1 ? '1 fustan' : `${n} fustane`),
    none: 'Asnjë tani',
    guide: 'Masat janë europiane: 34 është XS, 36 S, 38 M, 40 L, 42 XL.',
    label: (size: string, letter: string) => `Masa ${size} (${letter})`,
  },
  home: {
    openLookbook: 'Shiko fustanet',
  },
  shop: {
    title: 'Shop',
    contents: 'Indeksi',
    spreads: 'Faqet',
    count: (n: number) => (n === 1 ? '1 fustan' : `${n} fustane`),
    inSize: (n: number, size: string) => (n === 1 ? `1 fustan në masën ${size}` : `${n} fustane në masën ${size}`),
    empty: (size: string) => `Asnjë fustan në masën ${size} tani. Provo një masë tjetër ose pyet në Instagram.`,
    emptyCategory: 'Asnjë fustan në këtë kategori tani.',
    tagline: TAGLINE,
    open: 'Shiko fustanin',
    soldOut: 'E shitur',
  },
  product: {
    size: 'Masa',
    chooseSize: 'Zgjidh masën',
    add: 'Shto në çantë',
    added: 'U shtua në çantë',
    soldOut: 'E shitur',
    sizeSoldOut: (size: string) => `Masa ${size} është shitur`,
    lastOne: 'E fundit në këtë masë',
    description: 'Përshkrimi',
    delivery: 'Dërgesa dhe pagesa',
    deliveryBody: 'Paguan në dorëzim, kur e merr porosinë. Tarifa e transportit shfaqet te porosia.',
    deliveryZone: (zone: string, fee: string) => `${zone}: ${fee}`,
    feeByPhone: 'tarifa konfirmohet me telefon',
    instagram: 'Shiko në Instagram',
    ask: 'Pyet në Instagram',
    next: 'Fustani tjetër',
    back: 'Kthehu te fustanet',
    noPrice: 'Çmimi në Instagram',
    was: 'Më parë',
    share: 'Shpërndaje',
    copied: 'Lidhja u kopjua',
    video: 'Fustani në lëvizje',
    videoPlay: 'Luaj videon',
    videoPause: 'Ndalo videon',
    whatsapp: 'Pyet në WhatsApp',
    waText: (name: string, size: string | null, url: string) => `Përshëndetje! Më intereson fustani ${name}${size ? `, masa ${size}` : ''}. ${url}`,
    fit: 'Si bie:',
    measures: 'Masat',
    measuresNote: 'Në centimetra, të matura në fustan.',
    measure: { bust: 'Gjoksi', waist: 'Beli', hips: 'Ijet', length: 'Gjatësia:' },
    rentTitle: 'Merre me qera',
    rentIntro: 'Zgjidh datën e eventit dhe masën. Të shkruajmë me çmimin e qirasë dhe e konfirmojmë.',
    rentDate: 'Data e eventit',
    booked: 'E zënë më:',
    bookedOn: (d: string, size: string) => `${Number(d.slice(8, 10))} ${MONTHS_SQ[Number(d.slice(5, 7)) - 1]} (masa ${size})`,
    noteOptional: 'Shënim (jo i detyrueshëm)',
    rentSend: 'Dërgo kërkesën',
    rentDone: 'Kërkesa u dërgua. Të shkruajmë së shpejti.',
    restockTitle: 'Njoftomë kur kthehet masa',
    restockIntro: 'Lër numrin dhe të shkruajmë sapo masa të kthehet në gjendje.',
    restockSend: 'Njoftomë',
    restockDone: 'Faleminderit. Të shkruajmë kur të kthehet.',
    formCheck: 'Kontrollo fushat e shënuara.',
    formFailed: 'Nuk u dërgua. Provo përsëri pas pak.',
    newTag: 'E re',
  },
  bag: {
    title: 'Çanta',
    empty: 'Çanta jote është bosh.',
    emptyBody: 'Zgjidh një fustan në Shop dhe porosite këtu.',
    browse: 'Shiko fustanet',
    remove: 'Hiq',
    qty: 'Sasia',
    size: 'Masa',
    subtotal: 'Nëntotali',
    checkout: 'Vazhdo te porosia',
    unavailable: 'Nuk është më në gjendje',
    onlyLeft: (n: number) => (n === 1 ? 'Ka vetëm 1' : `Ka vetëm ${n}`),
    note: 'Transporti llogaritet te porosia. Paguan në dorëzim.',
  },
  checkout: {
    title: 'Porosia',
    contact: 'Të dhënat e tua',
    name: 'Emri dhe mbiemri',
    phone: 'Numri i telefonit',
    phoneHint: 'Të telefonojmë në këtë numër për ta konfirmuar porosinë.',
    email: 'Email (jo i detyrueshëm)',
    delivery: 'Dërgesa',
    zone: 'Zona',
    zones: { tirana: 'Tiranë', albania: 'Qytet tjetër në Shqipëri', kosovo: 'Kosovë' },
    city: 'Qyteti',
    address: 'Adresa',
    addressHint: 'Rruga, pallati, kati, apartamenti',
    notes: 'Shënime për dërgesën (jo të detyrueshme)',
    payment: 'Pagesa',
    cod: 'Pagesë në dorëzim',
    codBody: 'Paguan me para në dorë kur të vjen porosia.',
    card: 'Me kartë',
    cardBody: 'Paguan online me kartë debiti ose krediti.',
    summary: 'Përmbledhja',
    subtotal: 'Nëntotali',
    shipping: 'Transporti',
    shippingTbc: 'Konfirmohet me telefon',
    shippingFree: 'Falas',
    total: 'Totali',
    place: 'Dërgo porosinë',
    placing: 'Po dërgohet',
    emptyTitle: 'Çanta është bosh.',
    required: 'Plotëso këtë fushë.',
    phoneInvalid: 'Shkruaj një numër telefoni të vlefshëm, për shembull 069 123 4567.',
    emailInvalid: 'Shkruaj një adresë email të vlefshme, ose lëre bosh.',
    soldOut: (name: string, size: string) => `${name}, masa ${size}, nuk është më në gjendje. Hiqe nga çanta për të vazhduar.`,
    failed: 'Porosia nuk u dërgua. Provo përsëri pas pak.',
    consent: 'Duke dërguar porosinë pranon që dyqani të të telefonojë për ta konfirmuar.',
    edit: 'Ndrysho çantën',
  },
  confirmation: {
    label: 'Porosia nr.',
    title: (n: number) => `Porosia nr. ${n}`,
    thanks: 'Faleminderit. Porosia jote u regjistrua.',
    next: 'Dyqani do të të telefonojë për ta konfirmuar porosinë dhe për të caktuar dërgesën.',
    paid: 'Pagesa me kartë u krye.',
    unpaid: 'Paguan në dorëzim.',
    awaiting: 'Pagesa me kartë nuk është kryer ende.',
    retry: 'Paguaj me kartë',
    cancelled: 'Kjo porosi u anulua.',
    items: 'Fustanet',
    deliverTo: 'Adresa e dërgesës',
    continue: 'Vazhdo blerjet',
  },
  search: {
    title: 'Kërko',
    placeholder: 'Kërko fustane ose ngjyra',
    results: (n: number) => (n === 1 ? '1 fustan' : `${n} fustane`),
    none: 'Asnjë fustan me këtë emër. Provo një ngjyrë: e kuqe, blu, e zezë.',
    clear: 'Fshi',
    /** Words a visitor may type for each colour the admin suggests (search folds ë and ç away). */
    colors: {
      black: 'i zi e zezë të zeza',
      white: 'i bardhë e bardhë të bardha',
      red: 'i kuq e kuqe të kuqe',
      blue: 'blu i kaltër e kaltër',
      green: 'jeshil jeshile i gjelbër e gjelbër',
      pink: 'rozë',
      purple: 'vjollcë lejla',
      lilac: 'lejla jargavan',
      gold: 'ari i artë e artë',
      silver: 'argjend argjendi i argjendtë e argjendtë',
      grey: 'gri hiri',
      brown: 'kafe',
      yellow: 'i verdhë e verdhë të verdha',
    } as Record<string, string>,
  },
  visit: {
    title: 'Dyqani në Tiranë.',
    address: 'Rruga Andon Zako Çajupi, pas LSI, Tiranë',
    maps: 'Hap në Google Maps',
    body: "Eja t'i provosh në dyqan. Fustanet e reja dalin çdo javë në Instagram.",
    ask: 'Pyet në Instagram',
  },
  footer: {
    shop: 'Dyqani',
    help: 'Ndihmë',
    dresses: 'Fustanet',
    follow: 'Ndiq @dressesbygreta',
    followers: (n: number) => `${compact(n, 'sq')} ndjekës`,
    privacy: 'Kjo faqe nuk përdor cookies për reklama. Çanta ruhet vetëm në këtë pajisje.',
    rules: 'Rregullat e qirasë',
    city: 'Tiranë',
  },
  popup: {
    lead: 'Mos humb asgjë.',
    body: 'Fustanet e reja dalin çdo javë në Instagram.',
    cta: 'Ndiq në Instagram',
    close: 'Mbyll',
  },
  voices: {
    title: 'Nga klientet',
    dress: 'Fustani',
  },
  lookbook: {
    title: 'Lookbook',
    intro: 'Fustanet në histori: fotografi nga Greta, me fustanet e shënuara. Prek një numër për ta parë fustanin.',
    metaTitle: 'Lookbook, Dresses by Greta',
    metaDescription: 'Fotografi nga Dresses by Greta me fustanet e shënuara: prek një numër dhe shiko fustanin, çmimin dhe masat.',
    photos: (n: number) => (n === 1 ? '1 foto' : `${n} foto`),
    open: 'Shiko lookbook-un',
    inPhoto: 'Në këtë foto',
    view: 'Shiko fustanin',
    spot: (n: string, name: string) => `${n}: ${name}`,
  },
  me: {
    title: 'Masa dhe data',
    open: 'Masa dhe data',
    find: 'Gjej masën',
    yourSize: 'Masa jote',
    forDress: (size: string) => `Masa jote për këtë fustan: ${size}`,
    byDress: 'sipas masave të këtij fustani',
    byChart: 'sipas tabelës evropiane',
    change: 'Ndrysho',
    measuresTitle: 'Masat e tua',
    measuresHint: 'Në centimetra, të matura në trup. Mjafton edhe një.',
    tooBig: 'Asnjë masë nuk arrin. Na shkruaj dhe gjejmë një zgjidhje.',
    chartNote: 'Sipas tabelës evropiane. Te fustanet që kanë masat e veta, llogaritet me to.',
    orPick: 'Ose zgjidh masën',
    dateTitle: 'Data e eventit',
    dateHint: 'Dyqani të tregon cilët fustane janë të lirë për qira atë ditë.',
    clearDate: 'Hiq datën',
    privacy: 'Ruhen vetëm në këtë telefon, askund tjetër.',
    save: 'Ruaj',
    clear: 'Fshi të gjitha',
    free: (day: string) => `E lirë për qira më ${day}`,
    booked: (day: string) => `E zënë më ${day}`,
    bookedIn: (day: string, size: string) => `E zënë më ${day} në masën ${size}`,
    yoursSoldOut: (size: string) => `Masa jote (${size}) është shitur.`,
    notify: 'Njoftomë kur kthehet',
    day: (d: string) => `${Number(d.slice(8, 10))} ${MONTHS_SQ[Number(d.slice(5, 7)) - 1]}`,
  },
  stylist: {
    open: 'Stilistja AI',
    title: 'Stilistja AI',
    intro: 'Më trego eventin, ngjyrat që të pëlqejnë, masën dhe buxhetin. Të zgjedh deri në tre fustane nga dyqani.',
    label: 'Çfarë po kërkon?',
    example: 'Dasma e shoqes në tetor, diçka e gjatë dhe e thjeshtë, masa 38, deri në 25 mijë lekë.',
    context: (size: string | null, day: string | null) => `Mbaj parasysh atë që ke ruajtur te «Masa dhe data»: ${[size && `masa ${size}`, day].filter(Boolean).join(', ')}.`,
    ask: 'Pyet',
    asking: 'Po zgjedh fustanet',
    again: 'Pyet tjetër',
    note: 'Zgjedh Claude, një inteligjencë artificiale, vetëm nga fustanet e dyqanit. Kontrollo masën dhe çmimin te fustani.',
    privacy: 'Pyetja jote i dërgohet Anthropic, kompanisë që bën Claude, që të përgjigjet. Dyqani nuk e ruan. Mos shkruaj emrin apo telefonin.',
    errors: {
      short: 'Shkruaj pak më shumë: eventi, ngjyra, masa ose buxheti.',
      too_many: 'Ke pyetur shumë herë këtë orë. Provo pak më vonë.',
      limit: 'Stilistja nuk merr më pyetje për sot. Na shkruaj në Instagram.',
      busy: 'Stilistja është e zënë. Provo përsëri pas pak.',
      refused: 'Për këtë nuk mund të ndihmoj. Më trego fustanin që kërkon.',
      failed: 'Nuk munda të përgjigjem. Provo përsëri ose na shkruaj në Instagram.',
    },
  },
  saved: {
    save: 'Ruaj',
    saved: 'E ruajtur',
    title: 'Të ruajtura',
    count: (n: number) => (n === 1 ? '1 fustan' : `${n} fustane`),
    empty: 'Ende asnjë fustan i ruajtur. Shtyp «Ruaj» te një fustan dhe e gjen këtu.',
    share: 'Dërgoja dikujt',
    copied: 'Lidhja e listës u kopjua',
    shareText: 'Cili të pëlqen më shumë?',
    metaTitle: 'Të ruajtura, Dresses by Greta',
    metaDescription: 'Fustanet e ruajtura nga Dresses by Greta.',
  },
  motion: {
    stop: 'Ndalo animacionet',
    play: 'Lejo animacionet',
  },
  legal: {
    privacy: 'Privatësia',
    terms: 'Kushtet e shitjes',
  },
  pay: {
    title: 'Pagesa me kartë (test)',
    body: 'Kjo faqe imiton bankën vetëm në kompjuterin e zhvillimit. Asnjë kartë nuk tarifohet.',
    pay: 'Paguaj (test)',
    fail: 'Refuzo pagesën (test)',
  },
  notFound: {
    title: 'Kjo faqe nuk ekziston.',
    body: 'Ndoshta ky fustan nuk është më në shitje. Të tjerët janë këtu.',
    cta: 'Shiko fustanet',
  },
};

export type Copy = typeof sq;

const en: Copy = {
  lang: 'en',
  langName: 'English',
  langShort: 'EN',
  meta: {
    homeTitle: 'Evening dresses in Tirana · Prices in lek · Dresses by Greta',
    homeDescription: 'Evening, prom, wedding guest and cocktail dresses from the boutique in Tirana, priced in lek. Pick your size, order online and pay on delivery. Rental too.',
    shopTitle: 'Dresses online · Pay on delivery · Dresses by Greta',
    shopDescription: 'Every Dresses by Greta dress with its price and the sizes in stock. Order online and pay on delivery.',
    sizeTitle: (size: string) => `Dresses in size ${size}, Dresses by Greta`,
    checkoutTitle: 'Checkout, Dresses by Greta',
    notFoundTitle: 'Page not found, Dresses by Greta',
  },
  occasions: {
    heading: 'By occasion',
    usp: 'Prices in lek · Pay on delivery · Boutique in Tirana',
    rentAsk: 'Ask about renting on Instagram',
    evening: {
      label: 'Evening dresses',
      title: 'Evening dresses in Tirana · Prices in lek · Dresses by Greta',
      h1: 'Evening dresses in Tirana',
      description: 'Long evening dresses from the boutique in Tirana, with prices in lek and the sizes in stock. Order online and pay on delivery.',
      intro: 'Long dresses for galas, parties and ceremonies, from our boutique in Tirana. Every dress shows its price in lek and the sizes we have. Pick your size, order online and pay when it arrives, or come and try it on in the shop.',
    },
    prom: {
      label: 'Prom dresses',
      title: 'Prom dresses in Tirana · Prices in lek · Dresses by Greta',
      h1: 'Prom dresses',
      description: 'Long and short prom dresses with prices in lek. Order online in Tirana and pay on delivery.',
      intro: 'Dresses for prom night, long or short. See the price and the sizes in stock, order online and pay on delivery, or try it on in the shop in Tirana before the night.',
    },
    wedding: {
      label: 'Wedding guest dresses',
      title: 'Wedding guest dresses in Tirana · Prices in lek · Dresses by Greta',
      h1: 'Wedding guest dresses',
      description: 'Dresses for wedding guests, engagements and ceremonies, with prices in lek and the sizes in stock. Pay on delivery.',
      intro: 'Dresses for wedding guests, engagements and family ceremonies. Every dress shows its price in lek and the sizes we have. Order online and pay when it arrives.',
    },
    cocktail: {
      label: 'Cocktail dresses',
      title: 'Cocktail dresses in Tirana · Prices in lek · Dresses by Greta',
      h1: 'Cocktail dresses',
      description: 'Mini and midi cocktail dresses for birthdays, dinners and parties. Prices in lek, order online and pay on delivery.',
      intro: 'Mini and midi dresses for birthdays, dinners and parties. See the price and the sizes in stock, order online and pay on delivery.',
    },
    rental: {
      label: 'Dress rental',
      title: 'Dress rental in Tirana · Dresses by Greta',
      h1: 'Dress rental in Tirana',
      description: 'Rent an evening dress in Tirana from Dresses by Greta. Message us on Instagram with the dress, your size and the date of the event.',
      intro: 'You can also rent our dresses for an evening. Message us on Instagram with the name of the dress, your size and the date of the event, and we will confirm the rental price and whether the dress is free that day. Every dress below can also be bought online.',
    },
  },
  a11y: {
    skip: 'Skip to content',
    wordmark: 'Dresses by Greta, home',
    sizeIndex: 'Sizes',
    spreads: 'The dresses',
    gallery: 'Photos of the dress',
    close: 'Close',
    qtyDown: 'One fewer',
    qtyUp: 'One more',
    zoom: 'View the full photo',
    photoOf: (n: number, total: number) => `Photo ${n} of ${total}`,
    prev: 'Previous photo',
    next: 'Next photo',
    removeFilter: 'Remove filter',
  },
  demo: "Demo data: prices and stock are examples for testing, not the shop's.",
  nav: {
    menu: 'Menu',
    close: 'Close',
    search: 'Search',
    bag: 'Bag',
    region: 'Language',
    shop: 'Shop',
    lookbook: 'Shop',
    all: 'All dresses',
    bySize: 'By size',
    visit: 'The shop in Tirana',
    instagram: 'Instagram',
  },
  hero: {
    wordmark: 'Dresses by Greta',
    cta: 'See the dresses',
    alt: 'Long pink and mint tulle gown in a rose garden',
  },
  categories: { all: 'All', gowns: 'Gowns', mini: 'Mini & midi', black: 'Black', tv: 'Seen on TV', new: 'New' },
  sizes: {
    title: 'By size',
    all: 'All',
    count: (n: number) => (n === 1 ? '1 dress' : `${n} dresses`),
    none: 'None right now',
    guide: 'Sizes are European: 34 is XS, 36 S, 38 M, 40 L, 42 XL.',
    label: (size: string, letter: string) => `Size ${size} (${letter})`,
  },
  home: {
    openLookbook: 'See the dresses',
  },
  shop: {
    title: 'Shop',
    contents: 'Index',
    spreads: 'Pages',
    count: (n: number) => (n === 1 ? '1 dress' : `${n} dresses`),
    inSize: (n: number, size: string) => (n === 1 ? `1 dress in size ${size}` : `${n} dresses in size ${size}`),
    empty: (size: string) => `No dress in size ${size} right now. Try another size or ask on Instagram.`,
    emptyCategory: 'No dresses in this category right now.',
    tagline: TAGLINE,
    open: 'See the dress',
    soldOut: 'Sold out',
  },
  product: {
    size: 'Size',
    chooseSize: 'Choose your size',
    add: 'Add to bag',
    added: 'Added to bag',
    soldOut: 'Sold out',
    sizeSoldOut: (size: string) => `Size ${size} is sold out`,
    lastOne: 'Last one in this size',
    description: 'Description',
    delivery: 'Delivery and payment',
    deliveryBody: 'Pay on delivery, when the order reaches you. The delivery fee shows at checkout.',
    deliveryZone: (zone: string, fee: string) => `${zone}: ${fee}`,
    feeByPhone: 'fee confirmed by phone',
    instagram: 'View on Instagram',
    ask: 'Ask on Instagram',
    next: 'Next dress',
    back: 'Back to the dresses',
    noPrice: 'Price on Instagram',
    was: 'Was',
    share: 'Share',
    copied: 'Link copied',
    video: 'The dress in motion',
    videoPlay: 'Play the video',
    videoPause: 'Pause the video',
    whatsapp: 'Ask on WhatsApp',
    waText: (name: string, size: string | null, url: string) => `Hello! I am interested in the ${name} dress${size ? `, size ${size}` : ''}. ${url}`,
    fit: 'Fit:',
    measures: 'Measurements',
    measuresNote: 'In centimetres, measured on the dress.',
    measure: { bust: 'Bust', waist: 'Waist', hips: 'Hips', length: 'Length:' },
    rentTitle: 'Rent this dress',
    rentIntro: 'Choose the date of your event and your size. We will message you with the rental price and confirm.',
    rentDate: 'Event date',
    booked: 'Booked on:',
    bookedOn: (d: string, size: string) => `${Number(d.slice(8, 10))} ${MONTHS_EN[Number(d.slice(5, 7)) - 1]} (size ${size})`,
    noteOptional: 'Note (optional)',
    rentSend: 'Send request',
    rentDone: 'Request sent. We will message you soon.',
    restockTitle: 'Tell me when my size is back',
    restockIntro: 'Leave your number and we will message you as soon as the size is back in stock.',
    restockSend: 'Notify me',
    restockDone: 'Thank you. We will message you when it is back.',
    formCheck: 'Check the marked fields.',
    formFailed: 'It did not send. Try again in a moment.',
    newTag: 'New',
  },
  bag: {
    title: 'Bag',
    empty: 'Your bag is empty.',
    emptyBody: 'Choose a dress in the Shop and order it here.',
    browse: 'See the dresses',
    remove: 'Remove',
    qty: 'Quantity',
    size: 'Size',
    subtotal: 'Subtotal',
    checkout: 'Go to checkout',
    unavailable: 'No longer in stock',
    onlyLeft: (n: number) => (n === 1 ? 'Only 1 left' : `Only ${n} left`),
    note: 'Delivery is added at checkout. Pay on delivery.',
  },
  checkout: {
    title: 'Checkout',
    contact: 'Your details',
    name: 'Full name',
    phone: 'Phone number',
    phoneHint: 'We call this number to confirm the order.',
    email: 'Email (optional)',
    delivery: 'Delivery',
    zone: 'Area',
    zones: { tirana: 'Tirana', albania: 'Another city in Albania', kosovo: 'Kosovo' },
    city: 'City',
    address: 'Address',
    addressHint: 'Street, building, floor, flat',
    notes: 'Delivery notes (optional)',
    payment: 'Payment',
    cod: 'Pay on delivery',
    codBody: 'Pay in cash when the order arrives.',
    card: 'By card',
    cardBody: 'Pay online with a debit or credit card.',
    summary: 'Summary',
    subtotal: 'Subtotal',
    shipping: 'Delivery',
    shippingTbc: 'Confirmed by phone',
    shippingFree: 'Free',
    total: 'Total',
    place: 'Place order',
    placing: 'Sending',
    emptyTitle: 'Your bag is empty.',
    required: 'Fill in this field.',
    phoneInvalid: 'Enter a valid phone number, for example 069 123 4567.',
    emailInvalid: 'Enter a valid email address, or leave it empty.',
    soldOut: (name: string, size: string) => `${name}, size ${size}, is no longer in stock. Remove it from the bag to continue.`,
    failed: 'The order was not sent. Try again in a moment.',
    consent: 'By placing the order you agree that the shop may call you to confirm it.',
    edit: 'Edit the bag',
  },
  confirmation: {
    label: 'Order no.',
    title: (n: number) => `Order no. ${n}`,
    thanks: 'Thank you. Your order is in.',
    next: 'The shop will call you to confirm the order and arrange delivery.',
    paid: 'Card payment received.',
    unpaid: 'Pay on delivery.',
    awaiting: 'The card payment has not gone through yet.',
    retry: 'Pay by card',
    cancelled: 'This order was cancelled.',
    items: 'Dresses',
    deliverTo: 'Delivery address',
    continue: 'Continue shopping',
  },
  search: {
    title: 'Search',
    placeholder: 'Search dresses or colours',
    results: (n: number) => (n === 1 ? '1 dress' : `${n} dresses`),
    none: 'No dress by that name. Try a colour: red, blue, black.',
    clear: 'Clear',
    colors: { grey: 'gray', gold: 'golden', silver: 'silvery', lilac: 'lavender', purple: 'violet', pink: 'rose blush' },
  },
  visit: {
    title: 'The shop in Tirana.',
    address: 'Rruga Andon Zako Çajupi, pas LSI, Tiranë',
    maps: 'Open in Google Maps',
    body: 'Come and try them on in the shop. New dresses appear every week on Instagram.',
    ask: 'Ask on Instagram',
  },
  footer: {
    shop: 'The shop',
    help: 'Help',
    dresses: 'Dresses',
    follow: 'Follow @dressesbygreta',
    followers: (n: number) => `${compact(n, 'en')} followers`,
    privacy: 'This site uses no advertising cookies. Your bag is kept only on this device.',
    rules: 'Rental rules',
    city: 'Tirana',
  },
  popup: {
    lead: 'Stay in the know.',
    body: 'New dresses appear every week on Instagram.',
    cta: 'Follow on Instagram',
    close: 'Close',
  },
  voices: {
    title: 'From our clients',
    dress: 'The dress',
  },
  lookbook: {
    title: 'Lookbook',
    intro: 'The dresses in a story: photographs by Greta with the dresses marked. Tap a number to see the dress.',
    metaTitle: 'Lookbook, Dresses by Greta',
    metaDescription: 'Photographs by Dresses by Greta with the dresses marked: tap a number to see the dress, its price and sizes.',
    photos: (n: number) => (n === 1 ? '1 photo' : `${n} photos`),
    open: 'View the lookbook',
    inPhoto: 'In this photo',
    view: 'View the dress',
    spot: (n: string, name: string) => `${n}: ${name}`,
  },
  me: {
    title: 'Size and date',
    open: 'Size and date',
    find: 'Find my size',
    yourSize: 'Your size',
    forDress: (size: string) => `Your size for this dress: ${size}`,
    byDress: "from this dress's own measurements",
    byChart: 'from the European size chart',
    change: 'Change',
    measuresTitle: 'Your measurements',
    measuresHint: 'In centimetres, measured on the body. One is enough.',
    tooBig: 'No size reaches it. Message us and we will find a way.',
    chartNote: 'From the European size chart. Dresses with their own measurements use those.',
    orPick: 'Or pick your size',
    dateTitle: 'Your event date',
    dateHint: 'The shop shows which dresses are free to rent that day.',
    clearDate: 'Remove the date',
    privacy: 'Kept on this phone only, nowhere else.',
    save: 'Save',
    clear: 'Clear all',
    free: (day: string) => `Free to rent on ${day}`,
    booked: (day: string) => `Booked on ${day}`,
    bookedIn: (day: string, size: string) => `Booked on ${day} in size ${size}`,
    yoursSoldOut: (size: string) => `Your size (${size}) is sold out.`,
    notify: 'Tell me when it is back',
    day: (d: string) => `${Number(d.slice(8, 10))} ${MONTHS_EN[Number(d.slice(5, 7)) - 1]}`,
  },
  stylist: {
    open: 'AI stylist',
    title: 'AI stylist',
    intro: 'Tell me the event, the colours you like, your size and your budget. I choose up to three dresses from the shop.',
    label: 'What are you looking for?',
    example: "My friend's wedding in October, something long and simple, size 38, up to 25,000 lek.",
    context: (size: string | null, day: string | null) => `I will keep in mind what you saved in «Size and date»: ${[size && `size ${size}`, day].filter(Boolean).join(', ')}.`,
    ask: 'Ask',
    asking: 'Choosing dresses',
    again: 'Ask again',
    note: 'Chosen by Claude, an AI, only from the dresses in the shop. Check the size and price on the dress.',
    privacy: 'Your question is sent to Anthropic, the company that makes Claude, to be answered. The shop does not keep it. Do not write your name or phone number.',
    errors: {
      short: 'Write a little more: the event, a colour, your size or your budget.',
      too_many: 'You have asked many times this hour. Try again a little later.',
      limit: 'The stylist is not taking more questions today. Write to us on Instagram.',
      busy: 'The stylist is busy. Try again in a moment.',
      refused: 'I cannot help with that. Tell me about the dress you are looking for.',
      failed: 'I could not answer. Try again, or write to us on Instagram.',
    },
  },
  saved: {
    save: 'Save',
    saved: 'Saved',
    title: 'Saved',
    count: (n: number) => (n === 1 ? '1 dress' : `${n} dresses`),
    empty: 'No saved dresses yet. Press «Save» on a dress and it waits here.',
    share: 'Send to someone',
    copied: 'Link to the list copied',
    shareText: 'Which one do you like best?',
    metaTitle: 'Saved, Dresses by Greta',
    metaDescription: 'Saved dresses from Dresses by Greta.',
  },
  motion: {
    stop: 'Stop animations',
    play: 'Play animations',
  },
  legal: {
    privacy: 'Privacy',
    terms: 'Terms of sale',
  },
  pay: {
    title: 'Card payment (test)',
    body: 'This page stands in for the bank on the development machine only. No card is charged.',
    pay: 'Pay (test)',
    fail: 'Decline the payment (test)',
  },
  notFound: {
    title: 'This page does not exist.',
    body: 'This dress may no longer be on sale. The others are here.',
    cta: 'See the dresses',
  },
};

const fr: Copy = {
  lang: 'fr',
  langName: 'Français',
  langShort: 'FR',
  meta: {
    homeTitle: 'Robes de soirée à Tirana · Prix en lek · Dresses by Greta',
    homeDescription: 'Robes de soirée, de bal, d\'invitée et de cocktail de la boutique de Tirana, en lek. Choisissez votre taille, commandez en ligne et payez à la livraison. Location possible.',
    shopTitle: 'Robes en ligne · Paiement à la livraison · Dresses by Greta',
    shopDescription: 'Toutes les robes Dresses by Greta, avec leur prix et les tailles disponibles. Commandez en ligne et payez à la livraison.',
    sizeTitle: (size: string) => `Robes en taille ${size}, Dresses by Greta`,
    checkoutTitle: 'Commande, Dresses by Greta',
    notFoundTitle: 'Page introuvable, Dresses by Greta',
  },
  occasions: {
    heading: 'Par occasion',
    usp: 'Prix en lek · Paiement à la livraison · Boutique à Tirana',
    rentAsk: 'Demander une location sur Instagram',
    evening: {
      label: 'Robes de soirée',
      title: 'Robes de soirée à Tirana · Prix en lek · Dresses by Greta',
      h1: 'Robes de soirée à Tirana',
      description: 'Robes de soirée longues de la boutique de Tirana, avec le prix en lek et les tailles disponibles. Commandez en ligne et payez à la livraison.',
      intro: 'Des robes longues pour les galas, les fêtes et les cérémonies, de notre boutique de Tirana. Chaque robe indique son prix en lek et les tailles disponibles. Choisissez votre taille, commandez en ligne et payez à la réception, ou venez l\'essayer en boutique.',
    },
    prom: {
      label: 'Robes de bal',
      title: 'Robes de bal de promo à Tirana · Prix en lek · Dresses by Greta',
      h1: 'Robes de bal de promo',
      description: 'Robes de bal de promo, longues et courtes, avec le prix en lek. Commandez en ligne à Tirana et payez à la livraison.',
      intro: 'Des robes pour le bal de promo, longues ou courtes. Voyez le prix et les tailles disponibles, commandez en ligne et payez à la livraison, ou essayez-la en boutique à Tirana avant la soirée.',
    },
    wedding: {
      label: 'Robes d\'invitée',
      title: 'Robes d\'invitée de mariage à Tirana · Prix en lek · Dresses by Greta',
      h1: 'Robes d\'invitée de mariage',
      description: 'Robes pour les invitées de mariage, les fiançailles et les cérémonies, avec le prix en lek et les tailles disponibles. Paiement à la livraison.',
      intro: 'Des robes pour les invitées de mariage, les fiançailles et les cérémonies en famille. Chaque robe indique son prix en lek et les tailles disponibles. Commandez en ligne et payez à la réception.',
    },
    cocktail: {
      label: 'Robes de cocktail',
      title: 'Robes de cocktail à Tirana · Prix en lek · Dresses by Greta',
      h1: 'Robes de cocktail',
      description: 'Robes de cocktail mini et midi pour les anniversaires, les dîners et les fêtes. Prix en lek, commande en ligne et paiement à la livraison.',
      intro: 'Des robes mini et midi pour les anniversaires, les dîners et les fêtes. Voyez le prix et les tailles disponibles, commandez en ligne et payez à la livraison.',
    },
    rental: {
      label: 'Location de robes',
      title: 'Location de robes à Tirana · Dresses by Greta',
      h1: 'Location de robes à Tirana',
      description: 'Louez une robe de soirée à Tirana chez Dresses by Greta. Écrivez-nous sur Instagram avec la robe, votre taille et la date de l\'événement.',
      intro: 'Vous pouvez aussi louer nos robes pour une soirée. Écrivez-nous sur Instagram avec le nom de la robe, votre taille et la date de l\'événement, et nous vous confirmons le prix de la location et si la robe est libre ce jour-là. Chaque robe ci-dessous peut aussi être achetée en ligne.',
    },
  },
  a11y: {
    skip: 'Aller au contenu',
    wordmark: "Dresses by Greta, page d'accueil",
    sizeIndex: 'Tailles',
    spreads: 'Les robes',
    gallery: 'Photos de la robe',
    close: 'Fermer',
    qtyDown: 'Un de moins',
    qtyUp: 'Un de plus',
    zoom: 'Voir la photo en entier',
    photoOf: (n: number, total: number) => `Photo ${n} sur ${total}`,
    prev: 'Photo précédente',
    next: 'Photo suivante',
    removeFilter: 'Retirer le filtre',
  },
  demo: `Données de démonstration${NBSP}: les prix et les stocks sont des exemples de test, pas ceux de la boutique.`,
  nav: {
    menu: 'Menu',
    close: 'Fermer',
    search: 'Rechercher',
    bag: 'Panier',
    region: 'Langue',
    shop: 'Boutique',
    lookbook: 'Shop',
    all: 'Toutes les robes',
    bySize: 'Par taille',
    visit: 'La boutique à Tirana',
    instagram: 'Instagram',
  },
  hero: {
    wordmark: 'Dresses by Greta',
    cta: 'Voir les robes',
    alt: "Robe longue en tulle rose et vert d'eau dans un jardin de roses",
  },
  categories: { all: 'Toutes', gowns: 'Longues', mini: 'Mini & midi', black: 'Noires', tv: 'Vues à la télé', new: 'Nouveautés' },
  sizes: {
    title: 'Par taille',
    all: 'Toutes',
    count: (n: number) => (n === 1 ? '1 robe' : `${n} robes`),
    none: 'Aucune pour le moment',
    guide: `Tailles européennes${NBSP}: 34 correspond au XS, 36 au S, 38 au M, 40 au L, 42 au XL.`,
    label: (size: string, letter: string) => `Taille ${size} (${letter})`,
  },
  home: {
    openLookbook: 'Voir les robes',
  },
  shop: {
    title: 'Shop',
    contents: 'Index',
    spreads: 'Pages',
    count: (n: number) => (n === 1 ? '1 robe' : `${n} robes`),
    inSize: (n: number, size: string) => (n === 1 ? `1 robe en taille ${size}` : `${n} robes en taille ${size}`),
    empty: (size: string) => `Aucune robe en taille ${size} pour le moment. Essayez une autre taille ou écrivez-nous sur Instagram.`,
    emptyCategory: 'Aucune robe dans cette catégorie pour le moment.',
    tagline: TAGLINE,
    open: 'Voir la robe',
    soldOut: 'Vendue',
  },
  product: {
    size: 'Taille',
    chooseSize: 'Choisissez votre taille',
    add: 'Ajouter au panier',
    added: 'Ajoutée au panier',
    soldOut: 'Vendue',
    sizeSoldOut: (size: string) => `La taille ${size} est vendue`,
    lastOne: 'La dernière dans cette taille',
    description: 'Description',
    delivery: 'Livraison et paiement',
    deliveryBody: 'Vous payez à la livraison, à la réception de la commande. Les frais de livraison apparaissent au moment de la commande.',
    deliveryZone: (zone: string, fee: string) => `${zone}${String.fromCharCode(160)}: ${fee}`,
    feeByPhone: 'frais confirmés par téléphone',
    instagram: 'Voir sur Instagram',
    ask: 'Demander sur Instagram',
    next: 'Robe suivante',
    back: 'Retour aux robes',
    noPrice: 'Prix sur Instagram',
    was: 'Avant',
    share: 'Partager',
    copied: 'Lien copié',
    video: 'La robe en mouvement',
    videoPlay: 'Lire la vidéo',
    videoPause: 'Mettre la vidéo en pause',
    whatsapp: 'Demander sur WhatsApp',
    waText: (name: string, size: string | null, url: string) => `Bonjour ! La robe ${name}${size ? `, taille ${size}` : ''} m'intéresse. ${url}`,
    fit: `Coupe${NBSP}:`,
    measures: 'Mesures',
    measuresNote: 'En centimètres, mesurées sur la robe.',
    measure: { bust: 'Tour de poitrine', waist: 'Tour de taille', hips: 'Tour de hanches', length: `Longueur${NBSP}:` },
    rentTitle: 'Louer cette robe',
    rentIntro: "Choisissez la date de votre événement et votre taille. Nous vous écrivons avec le prix de la location et la confirmation.",
    rentDate: "Date de l'événement",
    booked: `Réservée le${NBSP}:`,
    bookedOn: (d: string, size: string) => `${Number(d.slice(8, 10))} ${MONTHS_FR[Number(d.slice(5, 7)) - 1]} (taille ${size})`,
    noteOptional: 'Remarque (facultatif)',
    rentSend: 'Envoyer la demande',
    rentDone: 'Demande envoyée. Nous vous écrivons bientôt.',
    restockTitle: 'Prévenez-moi du retour de ma taille',
    restockIntro: 'Laissez votre numéro et nous vous écrivons dès que la taille est de nouveau disponible.',
    restockSend: 'Prévenez-moi',
    restockDone: 'Merci. Nous vous écrivons à son retour.',
    formCheck: 'Vérifiez les champs signalés.',
    formFailed: "L'envoi a échoué. Réessayez dans un instant.",
    newTag: 'Nouveauté',
  },
  bag: {
    title: 'Panier',
    empty: 'Votre panier est vide.',
    emptyBody: 'Choisissez une robe dans le Shop et commandez-la ici.',
    browse: 'Voir les robes',
    remove: 'Retirer',
    qty: 'Quantité',
    size: 'Taille',
    subtotal: 'Sous-total',
    checkout: 'Passer la commande',
    unavailable: "N'est plus disponible",
    onlyLeft: (n: number) => (n === 1 ? 'Plus que 1' : `Plus que ${n}`),
    note: 'La livraison est calculée à la commande. Paiement à la livraison.',
  },
  checkout: {
    title: 'Commande',
    contact: 'Vos coordonnées',
    name: 'Nom et prénom',
    phone: 'Numéro de téléphone',
    phoneHint: 'Nous vous appelons à ce numéro pour confirmer la commande.',
    email: 'E-mail (facultatif)',
    delivery: 'Livraison',
    zone: 'Zone',
    zones: { tirana: 'Tirana', albania: 'Autre ville en Albanie', kosovo: 'Kosovo' },
    city: 'Ville',
    address: 'Adresse',
    addressHint: 'Rue, immeuble, étage, appartement',
    notes: 'Remarques pour la livraison (facultatif)',
    payment: 'Paiement',
    cod: 'Paiement à la livraison',
    codBody: 'Vous payez en espèces à la réception de la commande.',
    card: 'Par carte',
    cardBody: 'Vous payez en ligne par carte de débit ou de crédit.',
    summary: 'Récapitulatif',
    subtotal: 'Sous-total',
    shipping: 'Livraison',
    shippingTbc: 'Confirmée par téléphone',
    shippingFree: 'Gratuite',
    total: 'Total',
    place: 'Envoyer la commande',
    placing: 'Envoi en cours',
    emptyTitle: 'Votre panier est vide.',
    required: 'Remplissez ce champ.',
    phoneInvalid: 'Saisissez un numéro de téléphone valide, par exemple 069 123 4567.',
    emailInvalid: 'Saisissez une adresse e-mail valide, ou laissez le champ vide.',
    soldOut: (name: string, size: string) => `${name}, taille ${size}, n'est plus disponible. Retirez-la du panier pour continuer.`,
    failed: "La commande n'a pas été envoyée. Réessayez dans un instant.",
    consent: 'En envoyant la commande, vous acceptez que la boutique vous appelle pour la confirmer.',
    edit: 'Modifier le panier',
  },
  confirmation: {
    label: 'Commande n°',
    title: (n: number) => `Commande n°${NBSP}${n}`,
    thanks: 'Merci. Votre commande est enregistrée.',
    next: 'La boutique vous appellera pour confirmer la commande et organiser la livraison.',
    paid: 'Paiement par carte reçu.',
    unpaid: 'Paiement à la livraison.',
    awaiting: "Le paiement par carte n'a pas encore abouti.",
    retry: 'Payer par carte',
    cancelled: 'Cette commande a été annulée.',
    items: 'Robes',
    deliverTo: 'Adresse de livraison',
    continue: 'Continuer mes achats',
  },
  search: {
    title: 'Rechercher',
    placeholder: 'Rechercher une robe ou une couleur',
    results: (n: number) => (n === 1 ? '1 robe' : `${n} robes`),
    none: `Aucune robe de ce nom. Essayez une couleur${NBSP}: rouge, bleu, noir.`,
    clear: 'Effacer',
    colors: {
      black: 'noir noire',
      white: 'blanc blanche',
      red: 'rouge',
      blue: 'bleu bleue',
      green: 'vert verte',
      pink: 'rose',
      purple: 'violet violette',
      lilac: 'lilas mauve',
      gold: 'or doré dorée',
      silver: 'argent argenté argentée',
      grey: 'gris grise',
      brown: 'marron brun brune',
      yellow: 'jaune',
      teal: 'bleu canard',
    },
  },
  visit: {
    title: 'La boutique à Tirana.',
    address: 'Rruga Andon Zako Çajupi, pas LSI, Tiranë',
    maps: 'Ouvrir dans Google Maps',
    body: 'Venez les essayer en boutique. Les nouvelles robes arrivent chaque semaine sur Instagram.',
    ask: 'Demander sur Instagram',
  },
  footer: {
    shop: 'La boutique',
    help: 'Aide',
    dresses: 'Robes',
    follow: 'Suivre @dressesbygreta',
    followers: (n: number) => `${compact(n, 'fr')} abonnés`,
    privacy: "Ce site n'utilise aucun cookie publicitaire. Votre panier est gardé uniquement sur cet appareil.",
    rules: 'Règles de location',
    city: 'Tirana',
  },
  popup: {
    lead: 'Ne manquez rien.',
    body: 'Les nouvelles robes arrivent chaque semaine sur Instagram.',
    cta: 'Suivre sur Instagram',
    close: 'Fermer',
  },
  voices: {
    title: 'Nos clientes',
    dress: 'La robe',
  },
  lookbook: {
    title: 'Lookbook',
    intro: `Les robes en histoires${NBSP}: des photographies de Greta où les robes sont repérées. Touchez un numéro pour voir la robe.`,
    metaTitle: 'Lookbook, Dresses by Greta',
    metaDescription: `Des photographies de Dresses by Greta où les robes sont repérées${NBSP}: touchez un numéro pour voir la robe, son prix et ses tailles.`,
    photos: (n: number) => (n === 1 ? '1 photo' : `${n} photos`),
    open: 'Voir le lookbook',
    inPhoto: 'Sur cette photo',
    view: 'Voir la robe',
    spot: (n: string, name: string) => `${n}${NBSP}: ${name}`,
  },
  me: {
    title: 'Taille et date',
    open: 'Taille et date',
    find: 'Trouver ma taille',
    yourSize: 'Votre taille',
    forDress: (size: string) => `Votre taille pour cette robe${NBSP}: ${size}`,
    byDress: 'selon les mesures de cette robe',
    byChart: 'selon le guide des tailles européen',
    change: 'Modifier',
    measuresTitle: 'Vos mesures',
    measuresHint: 'En centimètres, prises sur le corps. Une seule suffit.',
    tooBig: 'Aucune taille ne convient. Écrivez-nous, nous trouverons une solution.',
    chartNote: 'Selon le guide des tailles européen. Les robes qui ont leurs propres mesures les utilisent.',
    orPick: 'Ou choisissez votre taille',
    dateTitle: 'Date de votre événement',
    dateHint: 'La boutique indique quelles robes sont libres à la location ce jour-là.',
    clearDate: 'Retirer la date',
    privacy: 'Gardées sur ce téléphone uniquement.',
    save: 'Enregistrer',
    clear: 'Tout effacer',
    free: (day: string) => `Libre à la location le ${day}`,
    booked: (day: string) => `Réservée le ${day}`,
    bookedIn: (day: string, size: string) => `Réservée le ${day} en taille ${size}`,
    yoursSoldOut: (size: string) => `Votre taille (${size}) est épuisée.`,
    notify: 'Prévenez-moi de son retour',
    day: (d: string) => `${Number(d.slice(8, 10))} ${MONTHS_FR[Number(d.slice(5, 7)) - 1]}`,
  },
  stylist: {
    open: 'Styliste IA',
    title: 'Styliste IA',
    intro: "Décrivez l'événement, les couleurs que vous aimez, votre taille et votre budget. Je choisis jusqu'à trois robes de la boutique.",
    label: `Que cherchez-vous${NBSP}?`,
    example: `Le mariage d'une amie en octobre, une robe longue et sobre, taille 38, jusqu'à 25${NBSP}000 lek.`,
    context: (size: string | null, day: string | null) =>
      `Je tiens compte de ce que vous avez enregistré dans «${NBSP}Taille et date${NBSP}»${NBSP}: ${[size && `taille ${size}`, day && `le ${day}`].filter(Boolean).join(', ')}.`,
    ask: 'Demander',
    asking: 'Je choisis les robes',
    again: 'Autre question',
    note: 'Choix faits par Claude, une IA, uniquement parmi les robes de la boutique. Vérifiez la taille et le prix sur la robe.',
    privacy: "Votre question est envoyée à Anthropic, l'entreprise qui développe Claude, pour y répondre. La boutique ne la conserve pas. N'écrivez ni votre nom ni votre téléphone.",
    errors: {
      short: `Écrivez un peu plus${NBSP}: l'événement, une couleur, votre taille ou votre budget.`,
      too_many: 'Vous avez posé beaucoup de questions cette heure-ci. Réessayez un peu plus tard.',
      limit: "La styliste ne prend plus de questions aujourd'hui. Écrivez-nous sur Instagram.",
      busy: 'La styliste est occupée. Réessayez dans un instant.',
      refused: 'Je ne peux pas aider pour cela. Décrivez la robe que vous cherchez.',
      failed: "Je n'ai pas pu répondre. Réessayez, ou écrivez-nous sur Instagram.",
    },
  },
  saved: {
    save: 'Enregistrer',
    saved: 'Enregistrée',
    title: 'Enregistrées',
    count: (n: number) => (n === 1 ? '1 robe' : `${n} robes`),
    empty: `Aucune robe enregistrée. Appuyez sur «${NBSP}Enregistrer${NBSP}» sur une robe pour la retrouver ici.`,
    share: "L'envoyer à quelqu'un",
    copied: 'Lien de la liste copié',
    shareText: `Laquelle préfères-tu${NBSP}?`,
    metaTitle: 'Enregistrées, Dresses by Greta',
    metaDescription: 'Les robes enregistrées chez Dresses by Greta.',
  },
  motion: {
    stop: 'Arrêter les animations',
    play: 'Réactiver les animations',
  },
  legal: {
    privacy: 'Confidentialité',
    terms: 'Conditions de vente',
  },
  pay: {
    title: 'Paiement par carte (test)',
    body: "Cette page simule la banque uniquement sur l'ordinateur de développement. Aucune carte n'est débitée.",
    pay: 'Payer (test)',
    fail: 'Refuser le paiement (test)',
  },
  notFound: {
    title: "Cette page n'existe pas.",
    body: "Cette robe n'est peut-être plus en vente. Les autres sont ici.",
    cta: 'Voir les robes',
  },
};

export const copy: Record<Lang, Copy> = { sq, en, fr };

/** Internal link that keeps the visitor's language (Albanian needs no parameter). */
export function href(path: string, lang: Lang, params: Record<string, string | undefined> = {}): string {
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) if (v) q.set(k, v);
  if (lang !== 'sq') q.set('lang', lang);
  const s = q.toString();
  return s ? `${path}?${s}` : path;
}
